on:
  push:
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_12

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: r-pkg-cache
          key: ${{ runner.os }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories(), Ncpu = 2L)
          remotes::install_cran('rcmdcheck', Ncpu = 2L)
          remotes::install_cran('covr', Ncpu = 2L)
          install.packages("Matrix")
        shell: Rscript {0}

      - name: Test coverage
        run: |
          options(warning.length = 8170)
          covr::codecov()
        shell: Rscript {0}
